import type { DJEvent } from "@/components/dj/dj-event.types";

// Today is 2026-04-02 (Thursday). Statuses come from the API, so they are fixed here.
export const MOCK_EVENTS: DJEvent[] = [
  // ── Past ─────────────────────────────────────────────────
  {
    id: "1",
    status: "done",
    name: "Night Fever",
    venue: "Fuego",
    address: "78 Jupiter St, Makati",
    category: "Club",
    date: "2026-03-28",
    startTime: "22:00",
    endTime: "04:00",
    entryPrice: 20,
    genres: ["House", "Disco"],
    coordinates: { lng: 121.0275, lat: 14.5575 },
  },
  {
    id: "2",
    status: "done",
    name: "Deep Cuts",
    venue: "The Vinyl Room",
    address: "92 Polaris St, Makati",
    category: "Lounge",
    date: "2026-03-31",
    startTime: "21:00",
    endTime: "03:00",
    genres: ["Soul", "RnB"],
    coordinates: { lng: 121.022, lat: 14.552 },
  },

  // ── Live (today, within 10PM–4AM window) ─────────────────
  {
    id: "3",
    status: "live",
    name: "Neon Dreams",
    venue: "Pulse",
    address: "123 Ayala Ave, Makati",
    category: "Nightclub",
    date: "2026-04-02",
    startTime: "22:00",
    endTime: "04:00",
    entryPrice: 15,
    genres: ["Techno", "House"],
    coordinates: { lng: 121.0244, lat: 14.5547 },
  },

  // ── Upcoming ─────────────────────────────────────────────
  {
    id: "4",
    status: "upcoming",
    name: "Concrete Jungle",
    venue: "Bass District",
    address: "15 Salcedo St, Makati",
    category: "Underground",
    date: "2026-04-05",
    startTime: "23:00",
    endTime: "06:00",
    entryPrice: 10,
    genres: ["DnB", "Techno"],
    coordinates: { lng: 121.0215, lat: 14.5605 },
  },
  {
    id: "5",
    status: "upcoming",
    name: "Wavelength",
    venue: "Noir Lounge",
    address: "45 P. Burgos St, Makati",
    category: "Bar",
    date: "2026-04-10",
    startTime: "21:00",
    endTime: "03:00",
    genres: ["Hip-Hop", "RnB", "Afrobeats"],
    coordinates: { lng: 121.026, lat: 14.5533 },
  },
  {
    id: "6",
    status: "upcoming",
    name: "Resonance",
    venue: "Elysium",
    address: "201 Makati Ave, Makati",
    category: "Nightclub",
    date: "2026-04-18",
    startTime: "22:00",
    endTime: "05:00",
    entryPrice: 25,
    genres: ["House", "Techno", "Disco"],
    coordinates: { lng: 121.028, lat: 14.555 },
  },
  {
    id: "7",
    status: "upcoming",
    name: "Sunset Sessions",
    venue: "Rooftop 88",
    address: "88 Rockwell Dr, Makati",
    category: "Rooftop",
    date: "2026-04-18",
    startTime: "17:00",
    endTime: "21:00",
    genres: ["Disco", "Soul"],
    coordinates: { lng: 121.036, lat: 14.565 },
  },
];
