// Generated by Cypress Author on 2026-08-05.

export type StubbedProfile = {
  profile_type: string | null;
};

declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * Stubs the network calls fired by pages the app can navigate to after a
       * successful login/signup (profile fetch, generic backend/Supabase REST
       * calls) so those destination pages don't hit the real network and can't
       * make an unrelated request flaky. Register this first in a test's
       * intercept setup — Cypress matches the most-recently-registered
       * intercept first, so flow-specific intercepts declared afterward still
       * take priority over these fallbacks.
       */
      stubPostAuthNetwork(profileType?: string | null): Chainable<void>;
    }
  }
}

Cypress.Commands.add("stubPostAuthNetwork", (profileType: string | null = null) => {
  cy.intercept("GET", "/api/backend/**", {
    statusCode: 200,
    body: { status: 200, message: "", data: [] },
  }).as("backendFallback");

  cy.intercept("GET", "**/rest/v1/**", { statusCode: 200, body: [] }).as("supabaseFallback");

  cy.intercept("GET", "/api/backend/users/*", {
    statusCode: 200,
    body: {
      status: 200,
      message: "",
      data: {
        id: "e2e-user-id",
        first_name: "Test",
        last_name: "User",
        display_name: "Test User",
        bio: null,
        genre_tags: [],
        country: null,
        socmed_links: null,
        profile_type: profileType,
        avatar_url: null,
      },
    },
  }).as("getProfile");
});

export {};
