// Generated by Cypress Author on 2026-08-05.
//
// Covers components/auth/LoginPage.tsx (route: /login). Network calls the
// page makes on submit are stubbed so the test stays deterministic and
// doesn't depend on a real Supabase project or backend:
//   1. POST /api/backend/auth/login          (lib/services/auth.ts)
//   2. POST **/auth/v1/token (grant_type=password)  (supabase-js)
//   3. GET  **/rest/v1/users?...             (direct profile_type lookup)

describe("Sign In", () => {
  beforeEach(() => {
    cy.stubPostAuthNetwork();
    cy.visit("/login");
  });

  it("renders the sign in form", () => {
    cy.contains("h1", "Welcome to Function Finder").should("be.visible");
    cy.get("#login-email").should("be.visible");
    cy.get("#login-password").should("have.attr", "type", "password");
    cy.contains("button", "Sign In").should("be.visible");
    cy.contains("a", "Sign Up").should("have.attr", "href", "/signup");
  });

  it("toggles password visibility", () => {
    cy.get("#login-password").type("whatever").should("have.attr", "type", "password");
    cy.get('[aria-label="Show password"]').click();
    cy.get("#login-password").should("have.attr", "type", "text");
    cy.get('[aria-label="Hide password"]').click();
    cy.get("#login-password").should("have.attr", "type", "password");
  });

  it("navigates to the sign up page", () => {
    cy.contains("a", "Sign Up").click();
    cy.location("pathname").should("eq", "/signup");
  });

  it("shows an error and stays on the page when credentials are rejected", () => {
    cy.intercept("POST", "/api/backend/auth/login", {
      statusCode: 401,
      body: { status: 401, message: "Invalid credentials", data: null },
    }).as("loginRequest");

    cy.fixture("auth").then(({ invalidCredentials }) => {
      cy.get("#login-email").type(invalidCredentials.email);
      cy.get("#login-password").type(invalidCredentials.password);
    });
    cy.contains("button", "Sign In").click();

    cy.wait("@loginRequest");
    cy.get('[role="alert"]').should("be.visible").and("contain.text", "Invalid email or password.");
    cy.location("pathname").should("eq", "/login");
  });

  it("signs in and redirects home when the account already has a profile", () => {
    cy.intercept("POST", "/api/backend/auth/login", {
      statusCode: 200,
      body: {
        status: 200,
        message: "",
        data: { access_token: "backend-token", refresh_token: "backend-refresh" },
      },
    }).as("backendLogin");
    cy.intercept("POST", "**/auth/v1/token*", {
      statusCode: 200,
      body: {
        access_token: "supabase-access-token",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "supabase-refresh-token",
        user: { id: "e2e-user-id", email: "e2e.user@example.com" },
      },
    }).as("supabaseSignIn");
    cy.intercept("GET", "**/rest/v1/users*", {
      statusCode: 200,
      body: { profile_type: "dj" },
    }).as("profileLookup");

    cy.fixture("auth").then(({ validCredentials }) => {
      cy.get("#login-email").type(validCredentials.email);
      cy.get("#login-password").type(validCredentials.password);
    });
    cy.contains("button", "Sign In").click();

    cy.wait("@backendLogin");
    cy.wait("@supabaseSignIn");
    cy.wait("@profileLookup");
    cy.location("pathname").should("eq", "/");
  });

  it("signs in and redirects to onboarding when the account has no profile yet", () => {
    cy.intercept("POST", "/api/backend/auth/login", {
      statusCode: 200,
      body: {
        status: 200,
        message: "",
        data: { access_token: "backend-token", refresh_token: "backend-refresh" },
      },
    }).as("backendLogin");
    cy.intercept("POST", "**/auth/v1/token*", {
      statusCode: 200,
      body: {
        access_token: "supabase-access-token",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "supabase-refresh-token",
        user: { id: "e2e-user-id", email: "e2e.user@example.com" },
      },
    }).as("supabaseSignIn");
    cy.intercept("GET", "**/rest/v1/users*", {
      statusCode: 200,
      body: { profile_type: null },
    }).as("profileLookup");

    cy.fixture("auth").then(({ validCredentials }) => {
      cy.get("#login-email").type(validCredentials.email);
      cy.get("#login-password").type(validCredentials.password);
    });
    cy.contains("button", "Sign In").click();

    cy.wait("@backendLogin");
    cy.wait("@supabaseSignIn");
    cy.wait("@profileLookup");
    cy.location("pathname").should("eq", "/onboarding");
  });

  it("carries the `next` redirect target through to onboarding", () => {
    cy.intercept("POST", "/api/backend/auth/login", {
      statusCode: 200,
      body: {
        status: 200,
        message: "",
        data: { access_token: "backend-token", refresh_token: "backend-refresh" },
      },
    }).as("backendLogin");
    cy.intercept("POST", "**/auth/v1/token*", {
      statusCode: 200,
      body: {
        access_token: "supabase-access-token",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "supabase-refresh-token",
        user: { id: "e2e-user-id", email: "e2e.user@example.com" },
      },
    }).as("supabaseSignIn");
    cy.intercept("GET", "**/rest/v1/users*", {
      statusCode: 200,
      body: { profile_type: null },
    }).as("profileLookup");

    cy.visit("/login?next=%2Fmap");
    cy.fixture("auth").then(({ validCredentials }) => {
      cy.get("#login-email").type(validCredentials.email);
      cy.get("#login-password").type(validCredentials.password);
    });
    cy.contains("button", "Sign In").click();

    cy.wait("@backendLogin");
    cy.wait("@supabaseSignIn");
    cy.wait("@profileLookup");
    cy.location("pathname").should("eq", "/onboarding");
    cy.location("search").should("eq", "?next=%2Fmap");
  });

  it("starts the Google OAuth redirect with the correct provider", () => {
    cy.intercept("GET", "**/auth/v1/authorize*", {
      statusCode: 200,
      headers: { "content-type": "text/html" },
      body: "",
    }).as("oauthRedirect");

    cy.get('[aria-label="Sign in with Google"]').click();

    cy.wait("@oauthRedirect").its("request.url").should("include", "provider=google");
  });

  //   it("starts the Facebook OAuth redirect with the correct provider", () => {
  //     cy.intercept("GET", "**/auth/v1/authorize*", {
  //       statusCode: 200,
  //       headers: { "content-type": "text/html" },
  //       body: "",
  //     }).as("oauthRedirect");

  //     cy.get('[aria-label="Sign in with Facebook"]').click();

  //     cy.wait("@oauthRedirect").its("request.url").should("include", "provider=facebook");
  //   });
});
