// Generated by Cypress Author on 2026-08-05.
//
// Covers components/auth/SignUpPage.tsx (route: /signup). Network calls the
// page makes on submit are stubbed so the test stays deterministic and
// doesn't depend on a real Supabase project or backend:
//   1. POST **/auth/v1/signup                (supabase-js)
//   2. POST /api/backend/auth/login           (lib/services/auth.ts, best-effort)
//   3. GET  /api/backend/users/:id             (profile fetch, via cy.stubPostAuthNetwork)

const VALID_PASSWORD = "SecurePass1";

describe("Sign Up", () => {
  beforeEach(() => {
    cy.visit("/signup");
  });

  it("renders the sign up form", () => {
    cy.contains("h1", "Create Account").should("be.visible");
    cy.get("#signup-name").should("be.visible");
    cy.get("#signup-email").should("be.visible");
    cy.get("#signup-password").should("have.attr", "type", "password");
    cy.get("#signup-confirm").should("have.attr", "type", "password");
    cy.contains("button", "Create Account").should("be.visible");
    cy.contains("a", "Sign In").should("have.attr", "href", "/login");
  });

  it("toggles password visibility independently for password and confirm", () => {
    cy.get("#signup-password").type(VALID_PASSWORD);
    cy.get("#signup-confirm").type(VALID_PASSWORD);

    // Password and confirm each render their own "Show password" toggle
    // button (scope to the sibling of the specific input rather than the
    // shared aria-label, which matches both) and are backed by independent
    // state, so toggling one must not affect the other.
    cy.get("#signup-password").siblings("button").click();
    cy.get("#signup-password").should("have.attr", "type", "text");
    cy.get("#signup-confirm").should("have.attr", "type", "password");

    cy.get("#signup-confirm").siblings("button").click();
    cy.get("#signup-confirm").should("have.attr", "type", "text");
    cy.get("#signup-password").should("have.attr", "type", "text");
  });

  it("navigates to the sign in page", () => {
    cy.contains("a", "Sign In").click();
    cy.location("pathname").should("eq", "/login");
  });

  it("flags an invalid email once the field is blurred, without submitting", () => {
    cy.intercept("POST", "**/auth/v1/signup*").as("signUpRequest");

    cy.get("#signup-email").type("not-an-email").blur();

    cy.contains("Enter a valid email address.").should("be.visible");
    cy.get("#signup-email").should("have.attr", "aria-invalid", "true");
    cy.get("@signUpRequest.all").should("have.length", 0);
  });

  it("lists live password requirements and blocks submission until they all pass", () => {
    cy.intercept("POST", "**/auth/v1/signup*").as("signUpRequest");

    cy.get("#signup-name").type("E2E Test User");
    cy.get("#signup-email").type("e2e.newuser@example.com");

    // No rule checklist before the user starts typing a password.
    cy.contains("At least 8 characters").should("not.exist");

    cy.get("#signup-password").type("weak");
    cy.contains("li", "At least 8 characters").should("be.visible");
    cy.contains("li", "One uppercase letter").should("be.visible");
    cy.contains("li", "One number").should("be.visible");
    cy.get("#signup-confirm").type("weak");

    cy.contains("button", "Create Account").click();

    // Weak password blocks submission before the confirm-match check ever runs.
    cy.get("@signUpRequest.all").should("have.length", 0);
    cy.location("pathname").should("eq", "/signup");
  });

  it("flags mismatched passwords and blocks submission", () => {
    cy.intercept("POST", "**/auth/v1/signup*").as("signUpRequest");

    cy.get("#signup-name").type("E2E Test User");
    cy.get("#signup-email").type("e2e.newuser@example.com");
    cy.get("#signup-password").type(VALID_PASSWORD);
    cy.get("#signup-confirm").type("SomethingElse1");
    cy.contains("button", "Create Account").click();

    cy.contains("Passwords do not match.").should("be.visible");
    cy.get("#signup-confirm").should("have.attr", "aria-invalid", "true");
    cy.get("@signUpRequest.all").should("have.length", 0);
    cy.location("pathname").should("eq", "/signup");
  });

  it("shows a friendly error when the email is already registered", () => {
    cy.intercept("POST", "**/auth/v1/signup*", {
      statusCode: 422,
      body: { error_code: "user_already_exists", msg: "User already registered" },
    }).as("signUpRequest");

    fillValidSignUpForm();
    cy.contains("button", "Create Account").click();

    cy.wait("@signUpRequest");
    cy.get('[role="alert"]')
      .should("be.visible")
      .and("contain.text", "An account with this email already exists.");
    cy.location("pathname").should("eq", "/signup");
  });

  it("shows a generic error when sign up fails for another reason", () => {
    cy.intercept("POST", "**/auth/v1/signup*", {
      statusCode: 500,
      body: { error_code: "unexpected_failure", msg: "Internal error" },
    }).as("signUpRequest");

    fillValidSignUpForm();
    cy.contains("button", "Create Account").click();

    cy.wait("@signUpRequest");
    cy.get('[role="alert"]')
      .should("be.visible")
      .and("contain.text", "Could not create account. Please try again.");
    cy.location("pathname").should("eq", "/signup");
  });

  it("creates the account and redirects a brand new user to onboarding", () => {
    cy.stubPostAuthNetwork(null);
    cy.intercept("POST", "**/auth/v1/signup*", {
      statusCode: 200,
      body: {
        access_token: "supabase-access-token",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "supabase-refresh-token",
        user: { id: "e2e-user-id", email: "e2e.newuser@example.com" },
      },
    }).as("signUpRequest");
    cy.intercept("POST", "/api/backend/auth/login", {
      statusCode: 200,
      body: {
        status: 200,
        message: "",
        data: { access_token: "backend-token", refresh_token: "backend-refresh" },
      },
    }).as("backendLogin");

    fillValidSignUpForm();
    cy.contains("button", "Create Account").click();

    cy.wait("@signUpRequest");
    cy.wait("@backendLogin");
    cy.location("pathname").should("eq", "/onboarding");
  });

  it("creates the account and redirects home when the user already has a profile", () => {
    cy.stubPostAuthNetwork("dj");
    cy.intercept("POST", "**/auth/v1/signup*", {
      statusCode: 200,
      body: {
        access_token: "supabase-access-token",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "supabase-refresh-token",
        user: { id: "e2e-user-id", email: "e2e.newuser@example.com" },
      },
    }).as("signUpRequest");
    cy.intercept("POST", "/api/backend/auth/login", {
      statusCode: 200,
      body: {
        status: 200,
        message: "",
        data: { access_token: "backend-token", refresh_token: "backend-refresh" },
      },
    }).as("backendLogin");

    fillValidSignUpForm();
    cy.contains("button", "Create Account").click();

    cy.wait("@signUpRequest");
    cy.wait("@backendLogin");
    cy.location("pathname").should("eq", "/");
  });

  //   it("starts the Google OAuth redirect with the correct provider", () => {
  //     cy.intercept("GET", "**/auth/v1/authorize*", {
  //       statusCode: 200,
  //       headers: { "content-type": "text/html" },
  //       body: "",
  //     }).as("oauthRedirect");

  //     cy.get('[aria-label="Sign up with Google"]').click();

  //     cy.wait("@oauthRedirect").its("request.url").should("include", "provider=google");
  //   });

  //   it("starts the Facebook OAuth redirect with the correct provider", () => {
  //     cy.intercept("GET", "**/auth/v1/authorize*", {
  //       statusCode: 200,
  //       headers: { "content-type": "text/html" },
  //       body: "",
  //     }).as("oauthRedirect");

  //     cy.get('[aria-label="Sign up with Facebook"]').click();

  //     cy.wait("@oauthRedirect").its("request.url").should("include", "provider=facebook");
  //   });
});

function fillValidSignUpForm() {
  cy.get("#signup-name").type("E2E Test User");
  cy.get("#signup-email").type("e2e.newuser@example.com");
  cy.get("#signup-password").type(VALID_PASSWORD);
  cy.get("#signup-confirm").type(VALID_PASSWORD);
}
